import "~/styles/globals.css";

import { Inter } from "next/font/google";
import {
  ClerkProvider,
  OrganizationSwitcher,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  auth,
} from "@clerk/nextjs";
import { redirect } from "next/navigation";
import { CheckoutButton } from "./api/stripe/client";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Projector | Modern Project Management",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <div
            className={`flex justify-between gap-5 px-5 py-2 ${inter.className}`}
          >
            Hello there, Stranger
            <SignedOut>
              <SignInButton>
                <button className="rounded bg-blue-300 p-2 px-4">
                  Sign In
                </button>
              </SignInButton>
            </SignedOut>
            <SignedIn>
              <div className="flex gap-4">
                <CheckoutButton />
                <OrganizationSwitcher />
                <UserButton afterSignOutUrl="/" />
              </div>
            </SignedIn>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
